### ISSUE TITLE
data-reveal-id makes pages invalid

### ISSUE THREAD

**Issue by johnpneumann** [zurb/reveal#11]
As a note this is obviously xhtml 1.0/1.1 and html 4 dependent since html5 allows for the custom data attribute.

I noticed that my pages were failing validation because of the `data-reveal-id` attribute. So I switched it to `rel` in my `<a href` calls and modified the jquery.reveal.js file like so:

```
/*---------------------------
 Listener for data-reveal-id attributes
----------------------------*/
    // @CHANGED - Made it so that it accepted the rel attribute instead of the data-reveal-id
    $('a[rel]').live('click', function(e) {
        e.preventDefault();
        var modalLocation = $(this).attr('rel');
        $('#'+modalLocation).reveal($(this).data());
    });
```

Since all of my links are launching modal windows this works fine for me, but if you're using lightbox or some other jquery script that attaches to rel as well, it may need to be modified to validate the string being passed. While this may not be a bug for some folks it was an issue for me and easily fixable. If this is not considered an issue I apologize.

**Comment by mkelly12** [comment]
Thanks for posting this, it's a good workaround for anyone else that wants their pages to pass validation and cannot use the html5 doctype.

I'll point people here that have concerns about passing validation.

**Comment by ghost** [comment]
Hi

My first post is a Thank You both ^^
...I just met the same issue and this workaround works perfect for me :-)
You made me happy and saved ma a lot of time and trouble.
