### ISSUE TITLE
IE6 background

### ISSUE THREAD

**Issue by imjared** [zurb/reveal#2]
Can you confirm that there's no ie6 support or that it's a bug? I'm leaning toward lack of support since it doesn't work out of the box in ie6. The overlay sticks to the bottom of the container and is about 20px high. I don't love ie6 any more than any of you, trust me, just wondering for clients' sake. Stellar modal otherwise!

Here's a screenshot:
http://screencast.com/t/aJt1bz4ww

**Comment by mkelly12** [comment]
Correct, reveal does not support IE6.
