### ISSUE TITLE
Add method to close modal programmaticaly

### ISSUE THREAD

**Issue by aquam8** [zurb/reveal#22]
Cory  [suggested to add the following to the reveal source code to enable the modal to be close programmaticaly (from Javascript).
[http://stackoverflow.com/questions/4884369/how-do-i-programmatically-close-an-open-jquery-reveal-js-modal-box]

 $.fn.hideModal = function(options){
  var self        = this,
      modal       = $(self),
      topMeasure  = parseInt(modal.css('top'));
  $('.reveal-modal-bg').css({'display' : 'none'});  
  modal.css({'visibility' : 'hidden', 'top' : topMeasure});
}

and use
$('#your_modal_box').hideModal()

That's well worthwhile.

Thank you Cory!

**Comment by mkelly12** [comment]
Hey Matt,

You can close (or open) the modal with the current code by triggering the reveal open or close event.

``` javascript
$('#yourModal').trigger('reveal:close');
```
