### ISSUE TITLE
issues with jQuery 1.6

### ISSUE THREAD

**Issue by petrhaus** [zurb/reveal#7]
Hi,
while testing with jQuery 1.6 I noticed that pop effects does not occur anymore, but fade works as expected... any idea what changed?

**Comment by mkelly12** [comment]
Animate in 1.6 no longer accepts just an integer for positions. So 10 no longer work, but 10px does. I just pushed a fix, let me know if you have any problems. a72aa4a8535d364ab9aeb79e406c7403825496ca
