### ISSUE TITLE
Feature Update Idea: Lightbox w/ Orbit & Reveal

### ISSUE THREAD

**Issue by marcwiest** [zurb/reveal#73]
Howdy Guys,

While I was looking for a lightbox for Foundation I had the idea of throwing an orbit into reveal which actually works quite well and maybe something to consider for future updates. [Have a quick look.](https://gist.github.com/marclarr/4979873)

Mostly what's missing is the ability to orbit-group scattered images from the page. Once bundled, we could initiate this orbit-group from within a reveal-modal container and have it open the clicked image instead of the first one from the orbit container.

**Comment by hatefulcrawdad** [comment]
We don't plan to add this functionality into the core of 3.2, sorry. It's an awesome idea, though, and we're glad you are experimenting.
